### ISSUE TITLE
USERSTORY: Opinion

### ISSUE THREAD

**Issue by JorgenBrattang** [JorgenBrattang/love-running#1]
As a **user** I can **provide my opinion to the love running project** so that **they can improve their site on the feedback they recieve.**

### Acceptance Criteria:
  - Acceptance Criteria 1: A text box for the opinion
  - Acceptance Criteria 2: A submit button to send the opinion
  - Acceptance Criteria 3: A reset button to reset the text field.
  
### Tasks
  - [ ] Add a text box with default text "Write your suggestion or opinion here".
  - [ ] Add a submit button.
  - [ ] Add a reset button.
  - [ ] Use HTML and CSS to design the layout.
  - [ ] Make the Submit button functional.
  - [ ] Make the Reset button functional.
  - [ ] Make the text box functional so it will contain the information when submited.
  - [ ] Test the functionality.

### Story Point estimation
3 point
#### Assumptions/rationale
- We need to create the module for the different parts and create the design for the poll.
- And create the core functionality to the whole process.
