### ISSUE TITLE
USERSTORY: anonymously

### ISSUE THREAD

**Issue by JorgenBrattang** [JorgenBrattang/love-running#2]
As a **user** I can **submit the opinion as anonymously** so that **I can't get recognize when I dont want to be.**

### Acceptance Criteria:
- Acceptance Criteria: A checkbox for the anonymously function
  
### Tasks
  - [ ] Implement a checkbox with default checked to the opinion.
  - [ ] Use HTML and CSS to design the layout next to submit button.
  - [ ] Make the checkbox functional, so the user is anonymous or not.
  - [ ] Test the functionality

### Story Point estimation
1 point
#### Assumptions/rationale
- We only need to implement one function to an already working code.
